SET "binary=sar.dll"
SET "src=..\bin\%binary%"
SET "dest=E:\Steam\SteamApps\common"

copy /Y "%src%" "%dest%\Portal 2\%binary%"
REM copy /Y "%src%" "%dest%\Aperture Tag\%binary%"
REM copy /Y "%src%" "%dest%\Portal Stories Mel\%binary%"
REM copy /Y "%src%" "%dest%\Portal\%binary%"
REM copy /Y "%src%" "%dest%\Half-Life 2\%binary%"
REM copy /Y "%src%" "%dest%\The Stanley Parable\%binary%"
REM copy /Y "%src%" "%dest%\The Beginners Guide\%binary%"
REM copy /Y "%src%" "%dest%\INFRA\%binary%"